config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  get "static_pages/index"
  get "static_pages/posts"

  resources :authors, only: :show
  resources :posts, only: [:index, :show] do
    collection do
      get :autocomplete
    end
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  scope :get_most_active_authors, (lambda do |author_number|
    find_by_sql("select a.name, a.id, count(p.id) as post_count
      from posts as p right outer join authors as a on p.author_id = a.id
      group by a.id order by post_count desc limit #{author_number}")
  end)
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author

  searchkick word_start: [:title], suggest: [:title],
    highlight: [:title, :content]

  scope :search_post, (lambda do |search_query, page|
    if search_query.nil?
      search paginate_options(page)
    else
      search search_query, search_options.merge(paginate_options(page))
    end
  end)

  scope :all_post_match_with, (lambda do |search_query|
    if search_query.nil?
      search
    else
      search search_query, search_options
    end
  end)

  def search_data
    {
      title: title,
      author: author.name,
      author_email: author.email,
      content: content
    }
  end

  class << self
    def search_options
      {
        highlight: {
          fields: [:title],
          fragment_size: Settings.post.fragment_size,
          tag: Settings.post.highlight_tag
        },
        suggest: true
      }
    end

    def paginate_options page
      {
        page: page, per_page: Settings.post.page
      }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def load_active_authors
    @active_authors = Author.get_most_active_authors(
      Settings.author.number_of_most_active
    )
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :load_author, only: :show

  def show; end

  private

  def load_author
    @author = Author.find_by id: params[:id]
    return if @author

    flash[:error] = "Not found"
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_active_authors, :search_post, only: :index

  def index; end

  def autocomplete
    render json: Post.search(params[:term], fields: [:title],
      match: :word_start, limit: 5).map(&:title).uniq
  end

  private

  def search_post
    @posts = Post.search_post params[:search], params[:page]

    respond_to do |format|
      format.json do
        render json: {
          posts: @posts.as_json(include: {
            author: {only: :name}
          }),
          suggestions: @posts.suggestions
        }
      end
      format.html
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :load_active_authors, only: :index
  before_action :all_posts, only: :posts

  def index
    render "static_pages/index"
  end

  def posts; end

  private

  def all_posts
    @posts = Post.all_post_match_with params[:search]

    respond_to do |format|
      format.json do
        render json: {
          posts: @posts.as_json(include: {
            author: {only: :name}
          }),
          suggestions: @posts.suggestions
        }
      end
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  FLASH_TYPE = {
    success: "alert-success", error: "alert-error", failed: "alert-failed",
    alert: "alert-info", notice: "alert-info", danger: "alert-danger"
  }.freeze

  def flash_class type
    FLASH_TYPE[type] || type.to_s
  end

  def post_content posts
    posts.with_highlights.map do |post, highlight_content|
      highlight_content.keys.each do |key|
        post.send (key.to_s + "=").to_sym, highlight_content[key]
      end
      post
    end
  rescue NoMethodError
    posts
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SearchkickDemo</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag "//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css" %>
  <%= javascript_include_tag "//code.jquery.com/ui/1.11.2/jquery-ui.js" %>
  <%= csrf_meta_tags %>
  <base href="/" />
</head>
<body>
  <%= yield %>

</body>
</html>

app/views/posts/_post.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h2 class="card-title">
      <%= link_to post.title.html_safe, post_path(post) %>
    </h2>
    <p class="card-text">
      <%= truncate(post.content, length: 1000, escape: false) %>
    </p>
    <%= link_to t("post.read_more"), post_path(post), class: "btn btn-primary" %>
  </div>
  <div class="card-footer text-muted">
    <%= t("post.posted_at", {time: time_ago_in_words(post.updated_at),
      author_name: link_to(post.author.name, author_path(post.author))}).html_safe %>
  </div>
</div>

app/views/posts/index.html.erb
<%= render "shared/search_bar" %>

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <% if @posts.suggestions.any? %>
        <%= render "shared/suggestion", suggestions: @posts.suggestions %>
      <% end %>
      <h1 class="my-4">
        <%= t "post.all_posts" %>
      </h1>
      <%= render post_content(@posts) %>
      <div class="justify-content-center mb-4">
        <%= will_paginate @posts, inner_window: Settings.post.inner_window %>
      </div>
    </div>
    <%= render "shared/active_authors" %>
  </div>
</div>

app/views/shared/_active_authors.html.erb
<div class="col-md-4">
  <div class="card my-4">
    <h5 class="card-header">
      <%= t "author.most_active" %>
    </h5>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-6">
          <ul class="list-unstyled mb-0">
            <% @active_authors.each do |author| %>
              <li>
                <%= link_to author.name, author_path(author) %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= flash_class type %> flash-notice">
    <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
    <p class="text-center flash-message"><%= message %></p>
  </div>
<% end %>

app/views/shared/_search_bar.html.erb
<ul class="navbar navbar-light bg-light justify-content-between">
  <%= link_to t("post.brand"), root_path, class: "navbar-brand" %>

  <%= form_tag(posts_path, {class: "form-inline", method: :get}) do %>
    <%= text_field_tag t("post.search"), params[:search], id: "post_search",
      class: "form-control mr-sm-2", placeholder: t("post.search"),
      "aria-label": "Search" %>
    <%= submit_tag t("post.search").capitalize,
      class: "btn btn-outline-success my-2 my-sm-0" %>
  <% end %>
</ul>

app/views/shared/_suggestion.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h2 class="card-title">
      <%= t "post.suggestion" %>
    </h2>
    <p class="card-text">
      <ul>
        <% suggestions.each do |suggestion| %>
          <li><%= link_to suggestion, posts_path(search: suggestion) %></li>
        <% end %>
      </ul>
    </p>
  </div>
</div>

app/views/static_pages/_post.html.erb
<div class="card mb-4" ng-repeat="post in posts track by $index">
  <div class="card-body">
    <h2 class="card-title">
      <a ng-href="/posts/{{post.id}}" ng-bind="post.title"></a>
    </h2>
    <p class="card-text" ng-bind="post.content | limitTo:1000"></p>
    <a ng-href="/posts/{{post.id}}" class="btn btn-primary">
      <%= t("post.read_more") %>
    </a>
  </div>
  <div class="card-footer text-muted">
    <posted-at></posted-at>
  </div>
</div>

app/views/static_pages/_search_bar.html.erb
<ul class="navbar navbar-light bg-light justify-content-between">
  <%= link_to t("post.brand"), root_path, class: "navbar-brand" %>
  <form class="form-inline">
    <input type="text" placeholder="search"
      aria-label="Search" ng-model="query" id="post_search"
      ng-change="search(query)" class="form-control mr-sm-2">
  </form>
</ul>

app/views/static_pages/_suggestion.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h2 class="card-title">
      <%= t "post.suggestion" %>
    </h2>
    <p class="card-text">
      <ul>
        <li ng-repeat="suggestion in suggestions track by $index">
          <a href="" ng-bind="suggestion" ng-click="search(null, suggestion)"></a>
        </li>
      </ul>
    </p>
  </div>
</div>

app/views/static_pages/index.html.erb
<div ng-app="app" class="container">
  <div ng-controller="PostsController">
    <%= render "search_bar" %>
    <div class="row">
      <div class="col-md-8">
        <div ng-if="error">
          <div class="alert alert-danger">
            <p ng-bind="error"></p>
          </div>
        </div>
        <div ng-if="suggestions.length">
          <%= render "suggestion" %>
        </div>
        <h1 class="my-4">
          <%= t "post.all_posts" %>
        </h1>
        <%= render "post" %>
        <uib-pagination total-items="totalItems" ng-model="currentPage" items-per-page="itemsPerPage" max-size="maxSize" boundary-links="true" rotate="false"></uib-pagination>
      </div>
      <%= render "shared/active_authors" %>
    </div>
  </div>
</div>